# Generated by Django 3.1.4 on 2021-01-04 18:42

import api_handler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api_handler.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
